config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'project/new'
  get 'project/show'
  post '/project', to:'project#create'
  get 'project/dashboard'
  root 'project#new'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project.rb
class Project < ApplicationRecord
    validates :name, presence: true
    validates :description, presence: true
    validates :state, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/project_controller.rb
class ProjectController < ApplicationController
    http_basic_authenticate_with name: "desafiovamoscontodo", password: "XAHTJEAS23123%23", only: :dashboard
    def new
        @project = Project.new
    end

    def show
        @project = Project.all
    end

    def create
        @project = Project.create(project_params)
        
    end
    def project_params
        { name: params[:name], description: params[:description], 
          start_date: params[:start_date], end_date: params[:end_date], state: params[:state]  }
    end

    def dashboard
        
        if params[:state].present?
            @projects = Project.where('state = ?', params[:state])
        else
            @projects = Project.all
        end
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/project_helper.rb
module ProjectHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Gestorproyecto</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/project/create.html.erb
<% if @project.errors.any? %>
    <div id ="error_explanation">
        <h2>
            <%= pluralize(@project.errors.count, "error") %>
            prohibited this user from being saved:
        </h2>
        <ul>
            <% @project.errors.full_messages.each do |msg|%>
            <li><%= msg %></li>
            <% end %>
        </ul>
    </div>
<% else %>
    <h1>Te proyecto fue creado con exito </h1>
<% end %>
<div>
    <%= link_to 'Crear Proyecto', project_new_path %>
</div>
<%= link_to 'Ver Proyectos', project_show_path %>

app/views/project/dashboard.html.erb
<h1 class="text-center mt-4 mb-4"> Dashboard </h1>

<form  id="filter">
            <select name="state" class ="mb-5">
                <option value="propuesta">Propuesta</option> 
                <option value="en progreso">En progreso</option>
                <option value="terminado">Terminado</option>
                <input type="submit" value="Filtrar" class="ml-3 mr-3">
                <%= link_to 'Refresh', project_dashboard_path %>
            </select>
</form>
            
            
<table class = "table">

    <tr>
      <th>Id</th>
      <th>Nombre</th>
      <th>Descripción</th>
      <th>Estado</th>
      <th>Fecha de comienzo</th>
      <th>Fecha de termino</th>

    </tr>
  <tbody>
    <% @projects.each do |project| %>
        <tr>
            <td><%= project.id%></td>
            <td><%= project.name%></td>
            <td><%= project.description%></td>
            <td><%= project.state%></td>
            <td><%= project.start_date%></td>
            <td><%= project.end_date%></td>
        </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'New', project_new_path %>

app/views/project/new.html.erb
<div class="container mt-5">
    <h1 class="text-center mb-5">Gestor Proyectos</h1>
    <form method="post" action="/project" id="create_project">
        <%= hidden_field_tag :authenticity_token, form_authenticity_token %> 
        <div class="ml-5">
            <h2>Nombre</h2>
            <input name="name" class ="mb-3">
            <h2>Descripción</h2>
            <textarea name="description" class ="mb-3"> </textarea>
            <h2>Fecha de comienzo</h2>
            <input type="date" name="start_date" value="2020-08-20" class ="mb-3" >
            <h2>Fecha de termino</h2>
            <input type="date" name="end_date" value="2020-08-20" class ="mb-3">
            <h2>Estado</h2>
            <select name="state" class ="mb-5">
                <option value="propuesta">Propuesta</option> 
                <option value="en progreso">En progreso</option>
                <option value="terminado">Terminado</option>
            </select>
        </div>
        <input type="submit" value="Enviar" class="ml-5 ">
        <div class="ml-5 mt-3 mb-5">
        <%= link_to 'Ver Proyectos', project_show_path %>
        </div>
    </form>
</div>

app/views/project/show.html.erb
<h1>Proyectos</h1>

<hr class="bg-dark">
<ul class="list-unstyled">
  <li class="media d-block">
    <% @project.each do |project| %>
      <div class="card-body">
        <h2 class="card-title"><%= project.name%></h2>
        <p class="card-text"><%= project.description%></p>
        <p class="card-text"><%= project.start_date%></p>
        <p class="card-text"><%= project.end_date%></p>
        <p class="card-text"><%= project.state%></p>
      </div>
      <hr class="bg-dark">
      <% end %>
  </li>

  <%= link_to 'Nuevo Proyecto', project_new_path %>